"""
Django settings for user_manager project.（user_manager项目的Django设置。）

Generated by 'django-admin startproject' using Django 1.10.2.（使用Django 1.10.2由' Django -admin startproject'生成。）

For more information on this file, see （有关此文件的更多信息看：）
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see（有关设置及其值的完整列表，请参见：）
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# 项目内部的构建路径如下:os.path。加入(BASE_DIR…)：
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# 快速启动开发设置-不适合生产，看：
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#安全警告:对生产中使用的密匙保密!
SECRET_KEY = '%gyxj*_@%rsq1er+asi=_w1ygsk)ju8t5+#5r)l0-lj3pzxrip'

# SECURITY WARNING: don't run with debug turned on in production!
# 安全警告:不要在生产环境中打开调试来运行!
DEBUG = True

ALLOWED_HOSTS = ["127.0.1.1"]


# Application definition （应用程序定义）
# 安装应用程序：
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app01',
]
# 中间件：
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
#管理员URL配置：
ROOT_URLCONF = 'user_manager.urls'

#模板
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#WSGI应用程序许可
WSGI_APPLICATION = 'user_manager.wsgi.application'


# Database（数据库）
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

#数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation（密码验证）
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

#身份验证密码验证器：
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization （国际化）
# https://docs.djangoproject.com/en/1.10/topics/i18n/

#语言代码：
LANGUAGE_CODE = 'en-us'
#时区：
TIME_ZONE = 'UTC'
#使用I18N
USE_I18N = True
#使用L10N
USE_L10N = True
#使用TZ
USE_TZ = True


# Static files (CSS, JavaScript, Images)静态文件(CSS, JavaScript，图片)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

#静态URL
STATIC_URL = '/static/'
#静态文件 目录
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
#会话引擎
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # 引擎（默认）
#会话COOKIE的名称
SESSION_COOKIE_NAME = "sessionid"  # Session的cookie保存在浏览器上时的key，即：sessionid＝随机字符串（默认）
#会话COOKIE路径
SESSION_COOKIE_PATH = "/"  # Session的cookie保存的路径（默认）
#会话COOKIE域
SESSION_COOKIE_DOMAIN = None  # Session的cookie保存的域名（默认）
#会话COOKIE安全
SESSION_COOKIE_SECURE = False  # 是否Https传输cookie（默认）
SESSION_COOKIE_HTTPONLY = True  # 是否Session的cookie只支持http传输（默认）
SESSION_COOKIE_AGE = 1209600  # Session的cookie失效日期（2周）（默认）
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 是否关闭浏览器使得Session过期（默认）
SESSION_SAVE_EVERY_REQUEST = False  # 是否每次请求都保存Session，默认修改之后才保存（默认）


